### ISSUE TITLE
チャット欄のコメントの背景を交互に色付ける機能

### ISSUE THREAD

**Issue by TsubasaHiga** [TsubasaHiga/SupachNumbering#80]
以下で適用出来そう。
``` css
yt-live-chat-text-message-renderer:nth-child(even) {
  background-color: var(--yt-live-chat-header-background-color);
}
```
